### PR TITLE
Auto-fix, modernization/cleanup, and more!

### LINKED ISSUE #1: Configuration
Hi, I installed the extension and tried to use it in a Javascript project with ESLint config, but there seems to be no linting executed. Do I need to configure something to get it to work?

### LINKED ISSUE #5: Project-specific eslint doesn't work
I don't have eslint installed globally but I do have it installed in the project I'm working on. I see that you use `/usr/bin/env eslint` which fails when I try it locally and won't pick up the project-specific installation but I believe you can call the project's version at `./node_modules/.bin/eslint` from the project root. Maybe this extension could check for a project-specific installation and fall back to a global installation?

I would have created a PR but I'm not familiar with Nova's extension setup, sorry. Let me know if I can help out though or provide more info.

### PR DESCRIPTION
**Pull request by apexskier**
I started writing a different plugin, then realized there were some improvements I wanted to make to yours. Because I originally wasn't working off your source, there are a lot of changes here. I'd rather not have competing extensions in the Library, though, so I'd like to contribute to yours.

* Add Prettier configuration, and format files with it (I've tried to match your syntax)
* Simplify source by not using classes where necessary and using more modern import/exports
* Upgrade all dependencies
* Simplify build scripts
* Switch to yarn. This is mostly person preference, but a big advantage is that it's way easier to manage merge conflicts in the lock file with it.

I've also added a few features

* Auto-fix command
* Auto-fix on save configuration
* Specify path to eslint executable configuration
* Kill running linters for a file before starting next lint pass
* More typescript support

And I've made one change that could be controversial

* Use workspace-local eslint (resolves #1 and resolves #5)  
  If a global eslint is needed, you can configure its path.

I'm also planning on a few things in the future.

* Add fallback to global eslint if installed, I just didn't get around to it, since local is much safer.
* Don't use eslint if no config is found in workspace
* Github actions PR tests

### CODE REVIEW

**Comment by jsmecham** [comment]
Hey, thanks for this! Haven’t had a chance to dive in yet, but will take a look over the next couple of days.

**Comment by gggritso** [comment]
I tried running this locally, but it refused to work! `document.uri` returns a string like `/Users/george/my-project/file:/Volumes/Macintosh%20HD/Users/george/my-project/some-file.js` and ESLint pukes up `ENOENT`. Changing the `lintDocument` function to use `document.path` fixed the issue, but I understand that won't work for unsaved files and so on 😢

**Comment by apexskier** [comment]
@gggritso That's really strange. I haven't seen paths like that before. I just pushed a change to normalize paths before trying to lint them, can you try that?

**Comment by apexskier** [comment]
Another option (but a largish refactor) is to use the [eslint nodejs api](https://eslint.org/docs/developer-guide/nodejs-api) directly (and use [`lintText`](https://eslint.org/docs/developer-guide/nodejs-api#◆-eslint-linttext-code-options)). This would allow both linting and fixing to work on unsaved files, but there's some trickiness in getting ahold of the project-level eslint version.

**Comment by gggritso** [comment]
@apexskier I think it might have been a Nova bug! I'm on b12 now, and the code works great before and after your patch!

**Comment by StefKors** [comment]
@apexskier @gggritso I would love to use these improvements in the latest b16 version. Does it run on b16??

**Comment by StefKors** [comment]
@apexskier @gggritso @jsmecham Anything I can do to get this merged and updated in the Nova extensions library? I would love to keep 1 eslint extension instead of having multiple versions because this isn't updated.

**Comment by jsmecham** [comment]
I'll be taking a look at bringing these changes into my project shortly. I may modify things to my preferences, however.

**Comment by apexskier** [comment]
Hey everyone, I just pushed some minor changes to how eslint executable setting work, to pull in some of what I've learned while writing https://github.com/apexskier/nova-typescript.

This is working fine for me on beta 17, I'm also hoping we can get it merged soon!

**Comment by atog** [comment]
@apexskier 's version works like a charm. Good work, thanks!

**Comment by henrikruscon** [comment]
Hows the progress on this?

**Comment by jsmecham** [comment]
I'm going to be working on this over the weekend before the release. Thank you everyone for your contributions!

**Comment by henrikruscon** [comment]
@jsmecham Looking forward to it. Let me know if you need any help.

**Comment by henrikruscon** [comment]
@apexskier Any reason the ESLint appears to be incredibly slow? Or is it a local issue for me? Testing your branch.

**Comment by apexskier** [comment]
> @apexskier Any reason the ESLint appears to be incredibly slow? Or is it a local issue for me? Testing your branch.

None that I know, no

**Comment by henrikruscon** [comment]
@apexskier Just to make sure, no as in you don't know what causes the slowdown or no as in you don't experience it as slow?

**Comment by apexskier** [comment]
> @apexskier Just to make sure, no as in you don't know what causes the slowdown or no as in you don't experience it as slow?

Both

**Comment by henrikruscon** [comment]
@jsmecham with Nova's official release being out now, you sure you don't want help to get this merged? ✌️

**Comment by jaydenseric** [comment]
@apexskier 

> I started writing a different plugin, then realized there were some improvements I wanted to make to yours. Because I originally wasn't working off your source, there are a lot of changes here. I'd rather not have competing extensions in the Library, though, so I'd like to contribute to yours.

Can you please publish a competing extension! Everyone I know can't use Nova because ESLint doesn't work. ESLint should always be installed and run as a project dev dependency.

**Comment by henrikruscon** [comment]
To be fair this was intended to be merged already in April this year, I think having this in a competing extension is the way to go by now.

**Comment by apexskier** [comment]
I've published a [fork](https://github.com/apexskier/nova-eslint) of this extension to the [Nova extension library](https://extensions.panic.com/extensions/apexskier/apexskier.eslint/). I've done a bit of work on [top of this PR](https://github.com/apexskier/nova-eslint/compare/apexskier...master), including properly disposing of listeners (which may have been contributing to @henrikdahl's slowness issues - there was exponential growth involved on each save) and converting to typescript (which exposed a few bugs).

**Comment by henrikruscon** [comment]
@apexskier Great work! Definitely feels faster now.

Seems that the config for fix on save is redundant right now, seems to always console the fixing message on save.

**Comment by apexskier** [comment]
Filed that here - https://github.com/apexskier/nova-eslint/issues/6

**Pull request closed without merging**
